# Generated by Django 5.0.6 on 2024-06-21 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_perms', '0001_initial'),
        ('entrances', '0002_alter_entrances_user_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='material',
        ),
        migrations.AddField(
            model_name='asignacion',
            name='id_detalle_entrada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entrances.detalleentrada'),
        ),
    ]
